"""Render phase_data_v2.json as markdown tables, in CN and EN editions.

Both editions are generated from the same dataset, so the two language versions
of the data appendix can never drift apart.

Run from anywhere:  python code/make_tables.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data", "phase_data_v2.json")
P = os.path.join(ROOT, "papers")

d = json.load(open(DATA, encoding="utf-8"))

TXT = {
    "CN": {
        "modeA": "模式 A：外生 Λ（p = 1 − 1/(1 + Λ·D_s/𝔅)）",
        "modeB": "模式 B：Λ × λ(n) 自适应（Theorem 7 接入）",
        "finite": "有限尺寸检验（模式 A，外生 Λ）",
        "head": "| Λ | Re ∝ 1/Λ | 结构密度 | sd | 各向异性 | sd | 谱斜率 | sd |",
        "fhead": "| N | Λ | 结构密度 | 谱斜率 | 各向异性 |",
        "src": ("数据来源：`data/phase_data_v2.json`，由 `code/export_v2.py` 生成"
                "（$N=60$，5 个种子 0–4）。`main_CN.md` / `main_EN.md` §6 引用的"
                "每个数值均出自此表，`code/audit.py` 自动核验对应关系。"),
    },
    "EN": {
        "modeA": "Mode A: exogenous Λ (p = 1 − 1/(1 + Λ·D_s/𝔅))",
        "modeB": "Mode B: Λ × λ(n) adaptive (Theorem 7 engaged)",
        "finite": "Finite-size check (Mode A, exogenous Λ)",
        "head": "| Λ | Re ∝ 1/Λ | structure density | sd | anisotropy | sd | spectral slope | sd |",
        "fhead": "| N | Λ | structure density | spectral slope | anisotropy |",
        "src": ("Source: `data/phase_data_v2.json`, regenerated by `code/export_v2.py`"
                " ($N=60$, five seeds 0–4). Every figure quoted in `main_CN.md` /"
                " `main_EN.md` §6 is drawn from this table; `code/audit.py` verifies"
                " the correspondence automatically."),
    },
}


def f(v, spec="%.4f"):
    """Render a possibly-null (NaN in the source data) value."""
    return "\u2014" if v is None else spec % v


for lang, t in TXT.items():
    L = []
    for mode, title in (("exogenous", t["modeA"]), ("adaptive", t["modeB"])):
        rows = d["modes"][mode]
        L.append("### " + title)
        L.append("")
        L.append(t["head"])
        L.append("|---:|---:|---:|---:|---:|---:|---:|---:|")
        for r in rows:
            L.append("| %.4g | %.4g | %s | %s | %s | %s | %s | %s |" % (
                r["lam"], r["re"],
                f(r["frac_neg"]), f(r["frac_neg_sd"]),
                f(r["anisotropy"]), f(r["anisotropy_sd"]),
                f(r["slope"], "%+.3f"), f(r["slope_sd"], "%.3f")))
        L.append("")

    L.append("### " + t["finite"])
    L.append("")
    L.append(t["fhead"])
    L.append("|---:|---:|---:|---:|---:|")
    for r in d["finite_size"]:
        L.append("| %d | %g | %.4f | %+.3f | %.4f |" % (
            r["n"], r["lam"], r["frac_neg"], r["slope"], r["anisotropy"]))
    L.append("")
    L.append("---")
    L.append("")
    L.append(t["src"])

    out = os.path.join(P, "tables_%s.md" % lang)
    open(out, "w", encoding="utf-8").write("\n".join(L))
    print("wrote", os.path.basename(out))
